/**
 * @file        main.c
 * @author      Wong Tat Hang (Alex)    thwongaz@connect.ust.hk
 * @brief       main entry for mesh processing and generation system built for 
 *              ISDN2400, ISDN1003 and ISDN1005 integrative project
 * @note        slic3r PE has to be installed and added to PATH
 * @date        28/4/2019
 * 
 * @copyright   Copyright (c) 2019
 */

#include <iostream>
#include <fstream>
#include "main.hpp"
#include "pressure.hpp"
using namespace std;

int main()
{
    system("rm ./output/*");
    float length, width, height;
    cout << "\nWelcone to the cushion generation software\n\n";
    cout << "Enter the length of the seating pad (mm): ";
    cin >> length;
    cout << "Enter the width of the seating pad  (mm): ";
    cin >> width;
    cout << "Enter the height of the seating pad (mm): ";
    cin >> height;
    cout << "\n";

    ofstream paramScad;
    paramScad.open("scad/param.scad", ios::out);
    paramScad << "// This file is auto generated by cpp/src/main.cpp\n";
    paramScad << "// using user input\n\n";
    paramScad << "padLength = " << length << ';' << '\n';
    paramScad << "padWidth = " << width << ';' << '\n';
    paramScad << "padHeight = " << height << ';' << '\n';
    paramScad.close();

    int pressureGenErrorCode = pressureGen();
    if(pressureGenErrorCode)
        return pressureGenErrorCode;

    system("openscad -o output/main.stl scad/mainBody.scad");
    cout << "Main Body Mesh Generation Successful";
    return 0;
}